---
title: "Working with Cal-Adapt Data in R Workshop - Welcome Email"
output: 
  html_document: 
    self_contained: no
    lib_dir: libs
---

```{css echo = FALSE}
h1 {
  font-size: 16px;
  font-weight: bold;
  margin-top:2em;
}
h1.title {
  font-size: 18px;
  font-weight: bold;
  color: black;
}
p {
  font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
}
.workshop-title {
  font-size: 18px;
  font-weight: bold;
  color: black;
}
```

\

*December 7, 2020*

Hi all,

Thank you for signing up for Friday's workshop on Working with Cal-Adapt data in R. I'm looking forward to meeting everyone and showing how you can use the new caladaptR package to import and work with Cal-Adapt data in R.

Below are a few details and notes about the workshop. If you have any questions please let me know.

Best,  
Andy

\

<p class="workshop-title">Working with Cal-Adapt Climate Data in R</p>
</b>Friday, December 11, 2020<br>
10:00 - 11:30am (PST)</p>

# Zoom Info

<a moz-do-not-send="true" href="https://ucanr.zoom.us/j/96522065994">https://ucanr.zoom.us/j/96522065994</a></p>

<p>Meeting ID: 965 2206 5994<br>
One tap mobile<br>
+16699006833,,96522065994# US (San Jose)<br>
+12532158782,,96522065994# US (Tacoma)<br>
Find your local number: <a class="moz-txt-link-freetext" href="https://ucanr.zoom.us/u/aeq6IwueG2"
moz-do-not-send="true">https://ucanr.zoom.us/u/aeq6IwueG2</a></p>

# Using a Second Monitor

<p>A second monitor is strongly recommended so you can view the instructor's screen in one monitor while you run R on the other. A tablet might suffice as your 'Zoom' device while you run R on your laptop. If you're truly limited to just one screen, check out <a moz-do-not-send="true" href="https://ucanr-igis.github.io/rspatial_scgis20/setup.html#viewing-rstudio-and-zoom-simultaneously">these tips</a> for viewing Zoom and an application window side-by-side. </p>

# Setting up R and RStudio

<p>This workshop is designed to be a hands-on, so you'll be using R a lot (you're free to simply watch of course). You have two choices for running R. You can run <b>RStudio Desktop</b> on your own laptop / desktop computer, or you can run a RStudio virtual machine from <b>RStudio Cloud</b> (in a browser). Both options are free. </p>

<p><b>Note</b>: We will not have time on Friday to help people setup their R environment. If you haven't installed all the required packages by 10am on Friday, you should still be able to pick up a lot by simply watching. </p>

<p><u>RStudio Cloud</u></p>

<p>The path of least resistance is to run RStudio Cloud. This is what I would recommend to most users who haven't touched R in a while, because you don't have to update R or install packages, and all the workshop materials will be waiting for you in the VM. If you never used RStudio Cloud before, it's well-developed and looks and feels nearly identical to RStudio desktop.</p>

<p>You can create a free account on <a moz-do-not-send="true" href="https://rstudio.cloud/">RStudio Cloud</a> with an email address or your Google or GitHub credentials. The free plan offers 15 hours of usage per month, which is more than enough for the workshop. Once your account is setup, you're done for now. On <b>Thursday night</b>, I'll send out a <b>link for the workshop VM</b>, which you can click on to make a clone in your own RStudio Cloud workspace. All the required packages and R notebooks will be ready to go.</p>

<p><u>RStudio Desktop</u></p>

<p>If its been more than 6 months since you updated <a moz-do-not-send="true" href="https://cran.r-project.org/">R</a> or <a moz-do-not-send="true" href="https://rstudio.com/products/rstudio/download/">RStudio Desktop</a>, please update them both. You should be using R version 3.6 or later. Windows users also need to install <a moz-do-not-send="true" href="https://cran.r-project.org/bin/windows/Rtools/">RTools</a> in order to install packages from GitHub (including caladaptr). </p>

<p>After you've updated R and RStudio, please copy-paste this <a moz-do-not-send="true" href="https://raw.githubusercontent.com/UCANR-IGIS/caladaptr/master/scripts/caladaptr_setup.R">setup script</a> into RStudio and run the commands to install the packages we'll be using during the workshop including caladaptr. This could take 15 minutes or longer so don't wait until Friday at 10am to start. The setup script also fetches some data using the Cal-Adapt API, so if you see a plot at the end it means its working.</p>

# Tech Support Drop-In Office Hours on Thursday December 10

<p>If you have any difficulty setting up R, I'll have drop-in office hours on Zoom on <b>Thursday December 10</b> from <b>11a-12p (PST)</b>, and <b>4-5p (PST)</b>. You can use the same Zoom link for the workshop above. Or email me if you encounter a problem beforehand.</p>

# Prerequisites

<p>As noted in the workshop description, this workshop presumes some <b>basic familiarity</b> with R. Most of the code examples will be ready-to-run so don't fret if you're a bit rusty. If you've never used R before, you're welcome to watch but we won't have time to trouble-shoot basic setup or syntax problems.</p>

<p>The workshop will include a high-level overview of the <b>Cal-Adapt datasets</b>, but not in any depth. If you're unfamiliar with climate data and terms like GCM or RCP, consider viewing the excellent webinar from the Cal-Adapt team on an <b><a moz-do-not-send="true" href="https://youtu.be/DGBzmyejws0">Introduction to Climate Data</a></b>.</p>

<p>Questions? Please contact the instructor.</p>


