---
title: "Computer Setup"
output: 
  html_document: 
    self_contained: no
    lib_dir: lib
    highlight: null
    mathjax: null
---

```{css echo = FALSE}
h1 {
  font-size: 18px;
  font-weight: bold;
  margin-top:2em;
  color:navy;
}
h1.title {
  font-size: 20px;
  font-weight: bold;
  color: #007020;
}
h2 {
  font-size: 16px;
  font-weight: bold;
  margin-top:2em;
}
p {
  font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
}
.workshop-title {
  font-size: 18px;
  font-weight: bold;
  color: black;
}

.indented1 {
  margin-left:1em;
}
```

\

# Setting up RStudio

If you would like to do the hands-on exercises during the workshop (recommended but not required), you have two options. You can run **RStudio Desktop** on your own laptop / desktop computer, or you can run a RStudio virtual machine from **RStudio Cloud** (i.e., in a browser). Both options are free and fairly easy to set up.

<div class="indented1">

## RStudio Cloud

The easiest way to do the workshop exercises is using **RStudio Cloud**. This is recommended for beginners and anyone who hasn't touched R in a while. With RStudio Cloud, all you need to do is set up an account. You don't have to install or update R and RStudio, install packages, download data, or any other set up. All the workshop materials will be waiting for you in a VM prepared by the instructor. If you never used RStudio Cloud before, it's well-developed and looks and feels nearly identical to RStudio Desktop.

You can create a free account on [RStudio Cloud](https://rstudio.cloud/){target="_blank" rel="noopener"} using an email address or your Google or GitHub credentials. The free plan offers 25 hours of usage per month, which is more than enough for the workshop. Once your account is setup, you're done for now. The day before the workshop, the instructor will send out a link for the workshop VM, which you can click on to make a copy of it in your own RStudio Cloud workspace. All the required packages, R notebooks, and data will be ready to go.

## RStudio Desktop

You can also run RStudio on your laptop. If its been more than 6 months since you updated [R](https://cran.r-project.org/){target="_blank" rel="noopener"} or [RStudio Desktop](https://rstudio.com/products/rstudio/download/){target="_blank" rel="noopener"}, please update them both. You should be using R version 3.6 or later. 

Windows users also need to install [RTools](https://cran.r-project.org/bin/windows/Rtools/){target="_blank" rel="noopener"} in order to install packages from GitHub (which includes caladaptR). As far as we know, all of the packages we'll be using (including caladaptR) should work fine on Windows, MacOS, and Linux.

After you've updated R and RStudio, please run [**this script**](https://github.com/ucanr-igis/caladaptr-res/blob/main/docs/workshops/ca_intro_oct21/scripts/caladaptr_setup.R){target="_blank" rel="noopener"} to **install all the needed packages** including `caladaptr` and `caladaptr.apps`. You can copy-paste the commands into RStudio and run the commands. This could take 15 minutes or longer so don't wait until the day of the workshop to start. If you get an error message installing any of the packages, please contact the instructor. 

The setup script also fetches some data using the Cal-Adapt API, so if you see a plot at the end it means its working.

\

*If you see this plot at the end of the setup script, it means everything is working:*

```{r test_calatapr, echo = FALSE, cache = TRUE, message = FALSE, out.width=500, out.height=300}
library(caladaptr); library(ggplot2); library(units); library(dplyr)

ca_example_apireq(1) %>%
  ca_getvals_tbl(quiet = TRUE) %>%
  mutate(temp_f = set_units(val, degF)) %>%
  ggplot(aes(x = as.Date(dt), y = as.numeric(temp_f))) +
  geom_line(aes(color=gcm)) +
  labs(title = "Daily Max Temp Averaged by Year, Sacramento, RCP4.5", x = "year", y = "temp (F)")
```

</div>  <!---- div class="indented1" --->

# Workshop Data and Materials

All workshop materials will be posted [on this website](https://ucanr-igis.github.io/caladaptr-res/workshops/ca_intro_oct21/){target="_blank" rel="noopener"}. The day before the workshop the instructor will send additional info including:

- For people using their laptops: a R command to run to download the notebooks and a small amount of data  

- For people using RStudio Cloud: a link to a VM they can click on to make a copy in their own workspace

# Using Two Monitors

A second monitor is strongly recommended so you can view the instructor's screen in one monitor while you run R on the other. A tablet might suffice as your 'Zoom' device while you run R on your laptop. 

If you're truly limited to just one screen, check out [these tips](workspace_tips.html) for viewing Zoom and an application window side-by-side.

# Questions?

If you have any questions please contact the [instructor](mailto:andlyons@ucanr.edu).

\

\
